// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0dFoTnpFQmbEp_qJNM3yHex64To4oXO4',
    appId: '1:804554152910:web:079315c3e71cfcfb3fa99f',
    messagingSenderId: '804554152910',
    projectId: 'ditonton-by-dicoding',
    authDomain: 'ditonton-by-dicoding.firebaseapp.com',
    storageBucket: 'ditonton-by-dicoding.appspot.com',
    measurementId: 'G-6ZH13Q7DJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRXkxuzMa4zvV0fdULj3oFEnfO3GPYrrI',
    appId: '1:804554152910:android:253fff62f62b75a63fa99f',
    messagingSenderId: '804554152910',
    projectId: 'ditonton-by-dicoding',
    storageBucket: 'ditonton-by-dicoding.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmdkCPQP2QGIiFWijpTrWi7ohseqcefIk',
    appId: '1:804554152910:ios:e0172d07d03284413fa99f',
    messagingSenderId: '804554152910',
    projectId: 'ditonton-by-dicoding',
    storageBucket: 'ditonton-by-dicoding.appspot.com',
    iosClientId: '804554152910-a1ashfspfah8187ev2lm26ujppmbe5ub.apps.googleusercontent.com',
    iosBundleId: 'com.belajarubic.ditonton',
  );
}
